### ISSUE TITLE
C++20: deprecated compound assignment to volatile variable

### ISSUE THREAD

**Issue by mumbleskates** [google/tcmalloc#106]
tcmalloc fails to build now with latest clang-14 in C++20 mode.

```
external/com_google_tcmalloc/tcmalloc/sampler.h:237:10: error: compound assignment to object of volatile-qualified type 'volatile ssize_t' (aka 'volatile long') is deprecated [-Werror,-Wdeprecated-volatile]
    *ptr += k;
         ^
```

Proposed solution:
```patch
diff --git a/tcmalloc/sampler.h b/tcmalloc/sampler.h
--- a/tcmalloc/sampler.h	(revision ea06ada5e31f4e5c6eb53f66da16d733cec1d7a3)
+++ b/tcmalloc/sampler.h	(date 1637277811947)
@@ -234,7 +234,7 @@
     // sub <reg>, <mem> instruction for subtraction above.
     volatile ssize_t *ptr =
         const_cast<volatile ssize_t *>(&bytes_until_sample_);
-    *ptr += k;
+    *ptr = *ptr + k;
     return false;
   }
   return true;
```

**Comment by mumbleskates** [comment]
This is new as of the addition of `-Werror` in 5d5968a72c5c378c3e41371628024ba2253d6b40 ; another option would be to add `-Wno-deprecated-volatile`, but it seems cleaner, easier, and better to simply fix the only occurrence of this warning.

**Comment by ckennelly** [comment]
Thanks for reporting this issue.

The code here is a bit convoluted so that we get a `sub [reg], [mem]` instruction.  It looks like `*ptr = *ptr + k` does the right thing on Clang 11 (but Clang 12 regressed, even the `*ptr += k` version that's currently checked in: https://godbolt.org/z/EnePx6h1f).

**Comment by mumbleskates** [comment]
ok! if it's needed the way it is and you have todos to keep it optimal when possible, it would make most sense to add `-Wno-deprecated-volatile` to suppress the warning, as you meant to do that and didn't mean to sting yourself with it when enabling `-Werror`.

**Comment by mumbleskates** [comment]
@ckennelly going by godbolt's output right now it looks like every clang version i check seems to do the right thing now. it looks like they all output both `sub     rax, rsi` and `add     qword ptr [rdi], rsi` for both versions of the function

**Comment by ckennelly** [comment]
@mumbleskates Even without the `volatile`?  The discussion in #137 suggests its at least still needed (so we still need the `-Wno-volatile`, unfortunately).

**Comment by mumbleskates** [comment]
@ckennelly as i understand it the suppressed warning is about using compound assignment operators on volatile variables, and rewriting it as `*ptr = *ptr + k` avoids the warning while having the same behavior; am i wrong that it generates the same assembly now?
