### ISSUE TITLE
Performance regression for redis

### ISSUE THREAD

**Issue by zhangningdlut** [google/tcmalloc#110]
I found preformance regression for redis when using this repo (vs tcmalloc in pgerftools).
With test:
```
echo always > /sys/kernel/mm/transparent_hugepage/enabled
redis-benchmark  -t set -n 10000000 -r 1000000000 -d 1024 -c 100
```
rps(with this repo, enable hpaa):223104.76
rps(with tcmalloc v4.5.9 in gperftools):183826.93

It has ~20% regression.
Is there some suggestion for using this tcmalloc?
Thanks!

**Comment by ckennelly** [comment]
The results you mention sound like a performance *improvement*.

As mentioned in https://abseil.io/blog/20200212-tcmalloc and https://google.github.io/tcmalloc/gperftools, this repository has a number of optimizations that gperftools lacks, so this result isn't entirely surprising.

**Comment by zhangningdlut** [comment]
> The results you mention sound like a performance _improvement_.
> 
> As mentioned in https://abseil.io/blog/20200212-tcmalloc and https://google.github.io/tcmalloc/gperftools, this repository has a number of optimizations that gperftools lacks, so this result isn't entirely surprising.

Sorry, I have pasted the result backwards.
The correct result is:
```
rps(with this repo, enable hpaa):183826.93
rps(with tcmalloc v4.5.9 in gperftools): 223104.76
```

**Comment by asamadiya** [comment]
@zhangningdlut Do you have numbers with hpaa disabled? I would have assumed gperftools malloc would be less performant.
