### ISSUE TITLE
Deadlock in production

### ISSUE THREAD

**Issue by vlovich** [google/tcmalloc#111]
We tried rolling out the new TCmalloc to replace our current gperftools usage but we get some deadlocks that are concerning:

```
/proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock_linux.inc in AbslInternalSpinLockDelay at line 66
/proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock_wait.h in absl::base_internal::SpinLockDelay at line 89
/proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.cc in absl::base_internal::SpinLock::SlowLock at line 159
/proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h in absl::base_internal::SpinLock::Lock at line 77
/proc/self/cwd/external/com_google_absl/absl/base/internal/spinlock.h in absl::base_internal::SpinLockHolder::SpinLockHolder at line 190
/proc/self/cwd/./tcmalloc/transfer_cache_internals.h in tcmalloc::tcmalloc_internal::internal_transfer_cache::RingBufferTransferCache at line 168
/proc/self/cwd/./tcmalloc/transfer_cache.h in tcmalloc::tcmalloc_internal::TransferCacheManager::InsertRange at line 255
/proc/self/cwd/./tcmalloc/cpu_cache.h in tcmalloc::tcmalloc_internal::cpu_cache_internal::CPUCache<T>::Overflow at line 1169
/proc/self/cwd/./tcmalloc/internal/percpu_tcmalloc.h in tcmalloc::tcmalloc_internal::subtle::percpu::TcmallocSlab_Internal_Push<T> at line 378
/proc/self/cwd/./tcmalloc/internal/percpu_tcmalloc.h in tcmalloc::tcmalloc_internal::subtle::percpu::TcmallocSlab<T>::Push at line 522
/proc/self/cwd/./tcmalloc/cpu_cache.h in tcmalloc::tcmalloc_internal::cpu_cache_internal::CPUCache<T>::Deallocate at line 418
/proc/self/cwd/tcmalloc/tcmalloc.cc in tcmalloc::tcmalloc_internal::FreeSmall<T> at line 1360
/proc/self/cwd/tcmalloc/tcmalloc.cc in tcmalloc::tcmalloc_internal::(anonymous namespace)::do_free_with_cl<T> at line 1731
/proc/self/cwd/tcmalloc/tcmalloc.cc in tcmalloc::tcmalloc_internal::(anonymous namespace)::do_free at line 1738
/proc/self/cwd/tcmalloc/tcmalloc.cc in TCMallocInternalFree at line 2122
```

Unfortunately we don't have a full dump of all threads so it's hard to know what the other threads are doing. This doesn't repro locally under test loads & only sporadically under production loads so it's hard to track down the root cause. Was wondering if maybe there are hints on how to debug this.

**Comment by ckennelly** [comment]
Which commit are you building at?  (From the line numbers, it looks like a recent one, but just want to double check...)

Did this start happening recently?

**Comment by vlovich** [comment]
We only have the stack for one trace. We don't have infra to capture the state of the other threads so looking for ideas on things to try/potential causes.

We synchronize the codebase weekly. We haven't been able to launch TCMalloc in production yet.

**Comment by ckennelly** [comment]
The callstack seems consistent with a thread taking the lock for the first time.  The `CPUCache` doesn't hold the `TransferCache`'s lock, and once we get to `InsertRange` we're running off of the lock annotations (`ABSL_LOCKS_EXCLUDED`).  The lock might already appear locked--but it's hard to draw many conclusions without knowing about what other threads might be doing and whether they were holding the lock.

1.  Did this particular pattern start happening *after* a particular commit?
2.  Were you able to exclude live locks?

**Comment by vlovich** [comment]
We've had trouble switching this TCMalloc on so I can't tie it to any specific commit. More likely to be something more fundamental like us hitting some unexpected limit/surprising sandbox violation or something. We had a related problem bumping up a memory limit that resulted in a similar pattern as our previous TCMalloc rollout attempt (crash on malloc (or was it free?) when put under load). That turned out to be that our `vm.max_map_count` was too low. We bumped it & tried rolling out TCMalloc again on the off chance that was the root cause. It still seemed to hit a deadlock under load again (it's fine on our lightly loaded machines).

A live lock seems unlikely I think unless TCMalloc might live-lock itself in this path?

**Comment by ckennelly** [comment]
It depends on what the other threads are doing to confirm, but given you mention this occurs *under load*, I'm suspicious of a live-lock since waiting threads might be starving the thread actually holding the lock.  A full dump of the stacks would indicate whether all of the threads appear to be waiting to acquire the lock (a likely deadlock situation) or if one of them plausibly holds the lock (a possible starvation situation).

To *debug* this, I would consider changing [`AbslInternalSpinLockDelay`](https://github.com/abseil/abseil-cpp/blob/master/absl/base/internal/spinlock_linux.inc#L59) to sleep indefinitely (`s/&tm/nullptr/`).  If that makes the apparent deadlocks go away, I think it confirms that a starvation situation.  Under high enough load, the waiters might be spinning and blocking the thread actually holding the lock from making progress.

There is a recent internal change here that I don't think has been pushed to Github yet.

**Comment by vlovich** [comment]
Thanks for the idea. I'll pass it along.
