### ISSUE TITLE
What is the intuition behind GWP-asan?

### ISSUE THREAD

**Issue by monkbai** [google/tcmalloc#114]
May I ask what the intuition behind GWP-asan is? More specifically, is there any benefit we can only get by applying the sampling-based GWP-asan but cannot get from the original ASan? Does it seem that all bugs that can be found by GWP-asan can also be found by ASan?

**Comment by fmayer** [comment]
Thanks for your question! The advantage of GWP-ASan is that it is effectively zero-overhead, and is meant to be used in production binaries rather than for testing. For testing, using ASan (or HWASan on ARM64) will allow to find more bugs.

**Comment by kcc** [comment]
+1 to the above. 
99.9% of bugs detected by GWP-ASan are also detectable with ASAN - if you can trigger them.  
We've seen a small set of bugs detectable by GWP-ASan and not by ASAN in its current form. 
Those were bad memory accesses inside libc or in assembly code - which ASAN doesn't instrument (currently).
