### ISSUE TITLE
Error during build on ubuntu 22.04

### ISSUE THREAD

**Issue by sinainnet** [google/tcmalloc#127]
Hi,

I was trying to build the tcmalloc on an ubuntu 22.04 machine. It gets an error for a missing package pypi__enum34. I have installed it using pypy-enum34 debian package.

Can anyone help me through this?

**Comment by ckennelly** [comment]
Do you have the full error message?  This is a C++ project, so it's not clear where pypi is coming into play.

**Comment by jwbee** [comment]
pypi is coming from the fuzzing deps:
```
external/fuzzing_py_deps/pypi__absl_py/BUILD:5:11: no such package '@fuzzing_py_deps//pypi__enum34': BUILD file not found in directory 'pypi__enum34' of external repository @fuzzing_py_deps. Add a BUILD file to a directory to mark it as a package. and referenced by '@fuzzing_py_deps//pypi__absl_py:pypi__absl_py'
ERROR: Analysis of target '//tcmalloc:malloc_extension_fuzz_corpus' failed; build aborted: 
```

**Comment by ckennelly** [comment]
Is there an open issue upstream with the fuzzing library for this?

**Comment by wangruitang** [comment]
> pypi is coming from the fuzzing deps:
> 
> ```
> external/fuzzing_py_deps/pypi__absl_py/BUILD:5:11: no such package '@fuzzing_py_deps//pypi__enum34': BUILD file not found in directory 'pypi__enum34' of external repository @fuzzing_py_deps. Add a BUILD file to a directory to mark it as a package. and referenced by '@fuzzing_py_deps//pypi__absl_py:pypi__absl_py'
> ERROR: Analysis of target '//tcmalloc:malloc_extension_fuzz_corpus' failed; build aborted: 
> ```

same as mine! Windows 10

**Comment by emesterhazy** [comment]
If you are still having this issue, please try with the change in #141 and let us know if it resolves the problem.
