### ISSUE TITLE
general incompatibility with run-time libraries & dlopen(..., RTLD_DEEPBIND)?

### ISSUE THREAD

**Issue by jroemmler** [google/tcmalloc#129]
Hello,
I've come across a case, that looks like a **general limitation** for tcmalloc use. It has to do with a `dlopen` call that prevents the libraries' dynamic memory functions from being replaced by tcmalloc:

I have a main program that is linked with `-ltcmalloc`. This program does a `dlopen()` to link a library at run-time. The library has a function that performs a `realloc()` call for a pointer that is passed in as argument (from the main program). The` realloc()` inside the library is replaced by `tc_realloc()` just fine, until I use `dlopen()` with flag `RTLD_DEEPBIND`. The result in this case is a `realloc()` call to libc for a pointer that was allocated before with `tc_malloc()`: => `abort()`.

Is this a known limitation of tcmalloc?

The reason I'm asking is because this is a real-world use case seen on my Linux x86_64 machine. It happens when certain system libraries are invoked, which in turn seem to call `dlopen()` in a manner that is incompatible with tcmalloc. My minimal test-case is attached (rename extension `.txt` back to `.c`)

[liba.txt](https://github.com/google/tcmalloc/files/8868009/liba.txt)
[main.txt](https://github.com/google/tcmalloc/files/8868011/main.txt)

BTW: The problem can be worked around by invoking the main program with `LD_PRELOAD=./liba.so`

Thanks!

**Comment by ckennelly** [comment]
My guess would be that `RTLD_DEEPBIND` is causing mixing-and-matching of which malloc implementation allocated the memory versus which one is deallocating (or reallocating).  `DEEPBIND` might be causing the library to prefer to call `libc`'s `realloc` rather than the one provided by TCMalloc.

Given the global state of malloc, it's not really feasible to support this.

**Comment by ruffianhy** [comment]
@jroemmler We can 't contact you via Altair email, we need your help with nlview lic website. Please contact huangyi@univista-isg.com if you see this message.
