### ISSUE TITLE
`calloc` implementation is much slower than ptmalloc

### ISSUE THREAD

**Issue by 372046933** [google/tcmalloc#131]
Possible duplicate: https://github.com/gperftools/gperftools/issues/22

In my benchmark setup,  for small objects, `malloc`, `posix_memalign` are ten time faster than ptmalloc implementation. But `calloc` is ten times slower than ptmalloc. Is this a known limitation?

**Comment by 372046933** [comment]
Version info:
```
Package: libgoogle-perftools4
Architecture: amd64
Version: 2.7-1ubuntu2
Multi-Arch: same
Priority: optional
Section: libs
Source: google-perftools
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Laszlo Boszormenyi (GCS) <gcs@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1051
Depends: libtcmalloc-minimal4 (= 2.7-1ubuntu2), libc6 (>= 2.29), libstdc++6 (>= 5.2), libunwind8
Conflicts: libgoogle-perftools0
Filename: pool/main/g/google-perftools/libgoogle-perftools4_2.7-1ubuntu2_amd64.deb
Size: 195244
MD5sum: 27bc056fc3cdef87592769bf682defe8
SHA1: b88512ccb126ec993b357a8b7c701b930aa62efc
SHA256: be06998b03fac2ed2e5a74911ff9ea41b63630a94bfddac496f5422b3d51c12a
Homepage: https://github.com/gperftools/gperftools
Description: libraries for CPU and heap analysis, plus an efficient thread-caching malloc
Description-md5: 9d3b2cf4c6afb08fb8e226be47a1fb1a
```

**Comment by alk** [comment]
Note that "google" in google-perftools is historic artifact. gperftools does not have any relation to Google for large number of years. Probably difficult for debian&ubuntu to rename the package.

**Comment by ckennelly** [comment]
TCMalloc does not optimize `calloc`.  Our experience is that it is extremely rare, so the extra state of tracking "known to be zero" is not worth the effort.

Additionally, @alk is correct and this project is distinct from gperftools.
