### ISSUE TITLE
Doesn't build with `--std=c++20` due to compound assignment to volatile

### ISSUE THREAD

**Issue by jwbee** [google/tcmalloc#137]
C++20 has deprecated most uses of `volatile`. At sampler.h:232-233 tcmalloc has this: 
```
    volatile ssize_t* ptr = const_cast<volatile ssize_t*>(&bytes_until_sample_);
    *ptr += k;
```
This causes the build to fail, unless using `-Wno-volatile`.

There are some explanatory comments about forcing compiler to emit optimal instruction, but in my program I am not getting the `sub <reg>, <mem>` that the comment suggests. I am getting `mov <reg>, <mem>; sub <reg>, <reg>` instead. Changing the code to this fixes the build and seems to generate the same asm, but since I wasn't getting the asm from the comments to begin with I am not sure this is the right fix.
```
auto t = *ptr;
t += k;
*ptr = t;
```

**Comment by ckennelly** [comment]
Clang 15 seems willing to generate the targeted assembly with `volatile`, and sets things up for a fusion opportunity with the jump:  https://godbolt.org/z/nj4Kof4s3

Including a non-`void` return seems to muddle things somewhat, since then we have some other work to possibly interleave--in practice, this gets heavily inlined anyways.  I used `asm volatile` with a memory clobber to simulate having a return value, to avoid getting too clever with conditional moves.

**Comment by jwbee** [comment]
Without the benefit of your context, it's a little hard to know why this snippet of code is performance-critical. It is the exceptional path, right? Is the issue that this is frequently inlined, and you'd prefer it didn't use a lot of registers?

Anyway, mostly just filing this to note the incompatibility. A reasonable fix would be to edit the README to say that tcmalloc requires exactly c++17, instead of at least that.

**Comment by ckennelly** [comment]
The codegen for the `sub <reg>, <mem>` is on the critical path, so it's nice to keep it to a handful of instructions (better icache pressure) and get the fusion of the adjacent flag-affecting operation and jump.  You're correct that the `volatile` is on an exception case, but LLVM at least seems to generate worse code for the preamble without it.

Is `-Wno-volatile`, added by #108, insufficient?

**Comment by jwbee** [comment]
I'll need to ponder that. Due to local customizations our clang toolchain's compiler attribute is not exactly called "clang", so that bazel select isn't working here. I have indeed added that warning flag to local configs for GCC. We didn't hit this until recent change of standard.
