### ISSUE TITLE
Create a shared object artifact of tcmalloc

### ISSUE THREAD

**Issue by Flowdalic** [google/tcmalloc#15]
It appears that tcmalloc's buildsystem is currently mostly written with static linking in mind. It would be great if there where a rule/target that produces a shared object of tcmalloc (potentially including dependencies like abseil).

**Comment by ckennelly** [comment]
As discussed on #16, including dependencies like Abseil can be problematic.  If a binary links against the TCMalloc shared object, it can't link against Abseil in an other way without triggering ODR issues.
