### ISSUE TITLE
Compile error on ARMv8 aarch64 Ubuntu platform.

### ISSUE THREAD

**Issue by esharkwang** [google/tcmalloc#156]
Hi,

When I use bazel 5.4.0 to compile the goolge fleetbench for aarch64 on Ubuntu server 20.04. I hit a compile failure with external dependency tcmalloc code.
Error log:

bazel build -c opt fleetbench/tcmalloc:all --spawn_strategy=local --sandbox_debug
INFO: Analyzed 8 targets (0 packages loaded, 0 targets configured).
INFO: Found 8 targets...
ERROR: /root/.cache/bazel/_bazel_root/0bce1989468318c371f4348e6ac4d902/external/com_google_tcmalloc/tcmalloc/BUILD:297:11: Compiling tcmalloc/global_stats.cc failed: (Exit 1): gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections ... (remaining 32 arguments skipped)
In file included from external/com_google_tcmalloc/tcmalloc/cpu_cache.h:39,
from external/com_google_tcmalloc/tcmalloc/global_stats.cc:21:
external/com_google_tcmalloc/tcmalloc/internal/percpu_tcmalloc.h: In function 'int tcmalloc::tcmalloc_internal::subtle::percpu::TcmallocSlab_Internal_Push(typename tcmalloc::tcmalloc_internal::subtle::percpu::TcmallocSlab::Slabs*, size_t, void*, tcmalloc::tcmalloc_internal::subtle::percpu::Shift, tcmalloc::tcmalloc_internal::subtle::percpu::OverflowHandler, void*, size_t)':
external/**com_google_tcmalloc/tcmalloc/internal/percpu_tcmalloc.h:667:9: error: expected ':' or '::' before '[' token
667 | : [end_ptr] "=&r"(end_ptr), [cpu_id] "=&r"(cpu_id),**
| ^
INFO: Elapsed time: 2.486s, Critical Path: 1.92s
INFO: 39 processes: 37 internal, 2 local.

here is the tcmalloc version referenced by fleetbench workspace.

http_archive(                                                                                                                                                [
    name = "com_google_tcmalloc",
    urls = ["https://github.com/google/tcmalloc/archive/48808681a9f38e974b49619a126f6f949ff59520.zip"],
    strip_prefix = "tcmalloc-48808681a9f38e974b49619a126f6f949ff59520",
    sha256 = "18bde75174866059a8db37dc42a921192b9182f57e7900a66d9f26cdd72599af",
)

**Comment by bendeguzvarju** [comment]
Hi, I have the exact same problem. If you got a solution, please share.

**Comment by esharkwang** [comment]
Hi @ckennelly ,
Could we upgrade the gcc in bazel to GCC 11.1? I will try to use bazel 6.0.0 as a workaround.

**Comment by esharkwang** [comment]
Yes, after I upgrade the gcc to gcc11 as the default. The issue was fixed. I can compile the binary now.
