### ISSUE TITLE
percpu_tcmalloc: !hdr.IsLocked() assertion failure

### ISSUE THREAD

**Issue by mikea** [google/tcmalloc#160]
We're seeing the following assertion failure in production:

```
./tcmalloc/internal/percpu_tcmalloc.h:1436] !hdr.IsLocked() 

/proc/self/cwd/tcmalloc/internal/logging.cc in tcmalloc::tcmalloc_internal::Crash at line 152
/proc/self/cwd/./tcmalloc/internal/percpu_tcmalloc.h in tcmalloc::tcmalloc_internal::subtle::percpu::TcmallocSlab<T>::ShrinkOtherCache at line 1436
/proc/self/cwd/./tcmalloc/cpu_cache.h in tcmalloc::tcmalloc_internal::cpu_cache_internal::CpuCache<T>::StealFromOtherCache at line 1221
/proc/self/cwd/./tcmalloc/cpu_cache.h in tcmalloc::tcmalloc_internal::cpu_cache_internal::CpuCache<T>::ShuffleCpuCaches at line 1076
/proc/self/cwd/tcmalloc/background.cc in MallocExtension_Internal_ProcessBackgroundActions at line 91
/proc/self/cwd/tcmalloc/malloc_extension.cc in tcmalloc::MallocExtension::ProcessBackgroundActions at line 472
```

This is from version fc357881b244df7010dde39dfa59968a9e93d4d8

**Comment by mikea** [comment]
> If you run TCMalloc's tests, in particular, //tcmalloc/internal:percpu_tcmalloc_test, are you able to reproduce the crash?

No. Even with `--runs_per_test=100` it works ok both in debug and release configuration.

I can't run it in production though. And it is nor a rare crash: it fails thousands times per day.

**Comment by mikea** [comment]
I've been reading the code and thinking how could this be happening. All code paths that lead to header locking seem to be protected by `resize_[src_cpu].lock`.

However, `StealFromOtherCache` has the structure:

```
<choose cache to steal>
<critical section> 
   ShrinkOtherCache
```

where one of the things being checked is `freelist_.Capacity` for a given class, which makes sure that the header is unlocked.

Do you think what could happen is for header to get lock between capacity check and critical section?  E.g. by Overflow/Refill happening on the user thread?

PS this is a really cool implementation, and rseqs are great!

**Comment by mikea** [comment]
meanwhile we're thinking of applying this patch:

```
diff --git a/tcmalloc/internal/percpu_tcmalloc.h b/tcmalloc/internal/percpu_tcmalloc.h
index 3abe1b7..59c0959 100644
--- a/tcmalloc/internal/percpu_tcmalloc.h
+++ b/tcmalloc/internal/percpu_tcmalloc.h
@@ -1433,7 +1433,7 @@ size_t TcmallocSlab<NumClasses>::ShrinkOtherCache(
   // Phase 1: Collect begin as it will be overwritten by the lock.
   std::atomic<int64_t>* hdrp = GetHeader(slabs, shift, cpu, size_class);
   Header hdr = LoadHeader(hdrp);
-  CHECK_CONDITION(!hdr.IsLocked());
+  if (hdr.IsLocked()) return 0;
   const uint16_t begin = hdr.begin;
 
   // Phase 2: stop concurrent mutations for <cpu> for size class <size_class>.
```

@ckennelly do you think it is a good idea while we figure out why this happens?

**Comment by mikea** [comment]
> If you sync back to [36d90dc](https://github.com/google/tcmalloc/commit/36d90dcb0520d82b3155d0052c998477e63bf837), that is, one commit prior to [a036e41](https://github.com/google/tcmalloc/commit/a036e4119f2e28f1c4bc901b07655cdb5a5fce60), do you run into the issue? That is the most recent nontrival change to the per-CPU cache, so it'd help gauge if this is a recent isuse.

Thanks. I'm rolling back our dependency and will let you know results later this week.

> Do your crashes have stack traces for any of your other threads? I'm curious if that could tell us if one of them is manipulating states concurrently.

Unfortunately no, we have thousands of threads and taking their traces is problematic. You can be sure that there are tons of concurrent allocations/deallocations: our workload is allocation heavy and we keep cpus hot.

**Comment by mikea** [comment]
@ckennelly I have good news and not so good news. Good news: our crashes in production are gone. Not so good news: we changed two things at the same time :)

Besides rolling back to 36d90dcb0520d82b3155d0052c998477e63bf837 we've applied a patch to absl to stop excessive spinning. Otherwise tcmalloc background thread was saturating full core. We have had this patch applied to gperf's version before, but when we first upgraded to new tcmalloc we haven't applied it yet.

Here's full patch for reference:

```patch
diff --git a/absl/base/internal/spinlock.cc b/absl/base/internal/spinlock.cc
index 381b913b..3a2d6104 100644
--- a/absl/base/internal/spinlock.cc
+++ b/absl/base/internal/spinlock.cc
@@ -88,12 +88,12 @@ SpinLock::SpinLock(base_internal::SchedulingMode mode)
 uint32_t SpinLock::SpinLoop() {
   // We are already in the slow path of SpinLock, initialize the
   // adaptive_spin_count here.
-  ABSL_CONST_INIT static absl::once_flag init_adaptive_spin_count;
-  ABSL_CONST_INIT static int adaptive_spin_count = 0;
-  base_internal::LowLevelCallOnce(&init_adaptive_spin_count, []() {
-    adaptive_spin_count = base_internal::NumCPUs() > 1 ? 1000 : 1;
-  });
-
+  // ABSL_CONST_INIT static absl::once_flag init_adaptive_spin_count;
+  ABSL_CONST_INIT static int adaptive_spin_count = 1;
+  // base_internal::LowLevelCallOnce(&init_adaptive_spin_count, []() {
+  //   adaptive_spin_count = base_internal::NumCPUs() > 1 ? 1000 : 1;
+  // });
   int c = adaptive_spin_count;
   uint32_t lock_value;
   do {
```


my current plan is to keep spin loop patch and roll tcmalloc forward. I'll give an update if the crash reappears.

**Comment by arun-vasudev** [comment]
We have been hitting this consistently in envoy proxy which statically links to the tcmalloc [9f385356](versionhttps://github.com/google/tcmalloc/commit/9f385356c34d4fc11f76a000b609e2b446c20667) (released in 2020-11-04) :-(

**Comment by dvyukov** [comment]
This function does not exist anymore, please re-test on HEAD.
