### ISSUE TITLE
O(n) behavior for large allocations

### ISSUE THREAD

**Issue by toddlipcon** [google/tcmalloc#20]
This re-released version of tcmalloc is missing the fix that's available in gperftools: https://github.com/gperftools/gperftools/commit/06c9414ec423ffe442c047b2560555f9d5847b1d

The O(n) search over large spans becomes very expensive for any long-running application with >1MB allocations, since over time the large span list can accumulate thousands of entries due to fragmentation.

**Comment by ckennelly** [comment]
TCMalloc has mostly moved to an alternative page heap implementation (Huge Page Aware Allocator), which doesn't use the same span list design.
