### ISSUE TITLE
Is there any release branch or tag of current project?

### ISSUE THREAD

**Issue by vinllen** [google/tcmalloc#212]
It looks like there is only one main branch in the current project, I've no idea whether it's a stable version.

**Comment by junyer** [comment]
The absence of tags/releases implies that TCMalloc follows the "live at head" philosophy _à la_ [Abseil](https://abseil.io/about/philosophy). [Bzlmod](https://bazel.build/external/overview) may necessitate explicit versioning in the not too distant future, however, so it's likely worth considering what model to support in that regard.

**Comment by ckennelly** [comment]
@junyer is correct in that we follow a "live at head" philosophy.
