### ISSUE TITLE
issue for "improve malloc fast path codegen"

### ISSUE THREAD

**Issue by PandaBlueYellow** [google/tcmalloc#213]
For this commit https://github.com/google/tcmalloc/commit/60282bf25bc58b21591da69555bb00f6b11162f7
When I use the numa aware tcmalloc, I hit this issue:
```
[tcmalloc/tcmalloc/internal/percpu.cc:117] sample_addr == sampler_alias_addr
```
cpu: intel
os: debian
compiler: clang 14

**Comment by ckennelly** [comment]
This optimization has been reimplemented in a different way, so there is no longer `sampler_alias_addr`.
