### ISSUE TITLE
Disabling tcmalloc cache

### ISSUE THREAD

**Issue by coder-saab001** [google/tcmalloc#216]
Hi community, is there is some way to disable the tcmalloc cache totally. We are working on minimising the memory usage of our system.

**Comment by junyer** [comment]
I doubt that any answer given here will differ substantially from the answer given on https://github.com/gperftools/gperftools/issues/1466.

**Comment by ckennelly** [comment]
@junyer is correct.  The caches hold onto freed objects by design, since they will likely be reused in the future.

TCMalloc has a number of heuristics to find unnecessary objects and flush them, but all of these are designed with a balance for CPU and RAM usage.
