### ISSUE TITLE
Could not find document about heap profiling with new tcmalloc

### ISSUE THREAD

**Issue by mzhaom** [google/tcmalloc#22]
Do we have anything similar to https://gperftools.github.io/gperftools/heapprofile.html or are still working on it?
Thanks!

**Comment by ckennelly** [comment]
The API in `malloc_extension.h` provides access to TCMalloc's heap profiler.  This covers

*  Snapshots (`tcmalloc::MallocExtension::SnapshotCurrent`), such as the sampled heap profile of current live objects.  We also collect a peak heap profile when the application heap (by user-accessible bytes) hits a high water mark.
*  An allocation profile (`tcmalloc::MallocExtension::StartAllocationProfiling`), to collect a time series of sampled allocations during that session.

We have not yet open-sourced a library for converting from this profile to the protocol buffer format understood by https://github.com/google/pprof.

**Comment by satyamshekhar** [comment]
Hello,

Is there a recommended workaround for this issue? Using TCMalloc without access to a usable view of the memory profile is very limiting for any serious development.

Also, I would love to learn about the timeline for the fix.

Regards,
Satyam

**Comment by alaxwang** [comment]
Na

> The API in `malloc_extension.h` provides access to TCMalloc's heap profiler. This covers
> 
> * Snapshots (`tcmalloc::MallocExtension::SnapshotCurrent`), such as the sampled heap profile of current live objects.  We also collect a peak heap profile when the application heap (by user-accessible bytes) hits a high water mark.
> * An allocation profile (`tcmalloc::MallocExtension::StartAllocationProfiling`), to collect a time series of sampled allocations during that session.
> 
> We have not yet open-sourced a library for converting from this profile to the protocol buffer format understood by https://github.com/google/pprof.

Any progress on open-sourced library for converting Profile to protocol buffer format understood by https://github.com/google/pprof.
It will be very useful to have a tool to looking at the memory profile.

**Comment by ckennelly** [comment]
As of 5d5968a72c5c378c3e41371628024ba2253d6b40, there is an interface (in tcmalloc/profile_marshaler.h, `tcmalloc::Marshal`) for converting from the profile instance collected by TCMalloc to a binary-encoded profile suitable for use with https://github.com/google/pprof.
