### ISSUE TITLE
How to access tcmalloc MallocExtensions?

### ISSUE THREAD

**Issue by CreativePSofficial** [google/tcmalloc#224]
Hello,

I currently have a program compiled with -ltcmalloc_minimal in the linker flags, which is sufficient to route all allocations to tcmalloc.

However, I was wondering how I could easily access MallocExtensions to do some custom stuff without directly including the entire tcmalloc source code into my build.

Thanks.

**Comment by ckennelly** [comment]
`-ltcmalloc_minimal` is coming from https://github.com/gperftools/gperftools.

`malloc_extension.h` evolves over time, so it needs to be directly included.
