### ISSUE TITLE
Does Google Use Standard Upstream Linux THP with TCMalloc?

### ISSUE THREAD

**Issue by marksantaniello** [google/tcmalloc#25]
We are wondering if Google might have some special internal implementation of kernel transparent huge pages (THP) that is somehow different from the upstream version.  Could you please confirm or deny this?

**Comment by ckennelly** [comment]
Yes, we use a stock version of THP.

The only noticeable non-default was commented in 20c77937f01e, in that `max_ptes_none=0`.
