### ISSUE TITLE
Is there benchmark between this tcmalloc and tcmalloc in gperftools?

### ISSUE THREAD

**Issue by T0mmyliu** [google/tcmalloc#26]

**Comment by ckennelly** [comment]
The two projects share a common ancestry, from Google's code base.  This repository is Google's current implementation of TCMalloc.

It has seen a number of optimizations to improve application productivity via optimizations to the implementation (per-CPU caches, sized delete, fast/slow path improvements, hugepage-aware backend).  Many of these techniques have little impact on raw `new` and `delete` performance, but instead improve the performance of everything else by reducing lock contention in the slow path and memory stalls in the application itself.  These have provided substantial application _macrobenchmark_ improvements.
