### ISSUE TITLE
Since macro __GLIBC__ is not defined in complier of Mac OS, how the libc_override.h works in Mac OS? 

### ISSUE THREAD

**Issue by dingsp** [google/tcmalloc#30]
#if defined(OS_WINDOWS)
// We don't do any overriding on windows. Just provide a dummy function.
static void ReplaceSystemAlloc() { }

#elif defined(GLIBC)
#include "tcmalloc/libc_override_glibc.h"

#else
#error Need to add support for your libc/OS here

#endif

The code has only two branches with two macros and who defines macro OS_WINDOWS? It seems like a user defined macro but I can't find it.

**Comment by dingsp** [comment]
`
#if defined(OS_WINDOWS)
// We don't do any overriding on windows.  Just provide a dummy function.
static void ReplaceSystemAlloc() { }

#elif defined(__GLIBC__)
#include "tcmalloc/libc_override_glibc.h"

#else
#error Need to add support for your libc/OS here

#endif`


the code has only two branches

**Comment by ckennelly** [comment]
TCMalloc does not support MacOS: https://google.github.io/tcmalloc/platforms.html

**Comment by dingsp** [comment]
Thanks to @ckennelly.

Constantly, can't find where the macro OS_WINDOWS is defined.

**Comment by ckennelly** [comment]
`OS_WINDOWS` was a vestigial reference (since cleaned up in aaac86fabe11b5234daaa04f86944968ac5f6eb3).
