### ISSUE TITLE
Segmentation fault when building with ASan

### ISSUE THREAD

**Issue by djwenren** [google/tcmalloc#42]
I always get segmentation fault when building with ASan on. Here is the way to trigger the problem
```
bazel run --copt=-fsanitize=address --linkopt=-fsanitize=address tcmalloc/testing:hello_main
``` 
It appears the seg fault happens before the main function is called as I added a quick print as the first statement in main and it was not printed. The seg fault goes away if I remove the "malloc = "//tcmalloc" in the cc_binary target.

I use the LLVM 10 toolchain on Ubuntu 20.04. Bazel version 3.4.1. TCMalloc is at commit 65bf45558405312282b71b212f77827bc16bd683.

**Comment by ckennelly** [comment]
AddressSanitizer provides its own copy of malloc and related functions, which is likely conflicting with the one provided by TCMalloc.
