### ISSUE TITLE
Why is LD_PRELOAD something you "don't necessarily recommend"

### ISSUE THREAD

**Issue by rodesai** [google/tcmalloc#45]
The tcmalloc page (http://goog-perftools.sourceforge.net/doc/tcmalloc.html) mentions that running with LD_PRELOAD is tricky and something you don't necessarily recommend, but doesn't go into detail about why. AFAICT possible issues include:
    - LD_PRELOAD is ignored if the setuid bit is set.
    - LD_PRELOAD would be inherited by any forked children, which may not be deseriable.

Anything else I'm missing?

**Comment by ckennelly** [comment]
The SourceForge page mentioned is unrelated to this repository.

Nonetheless, there's a discussion in #16 which discusses some of the pitfalls around ODR violations.
