### ISSUE TITLE
Question: Is it possible to force tcmalloc to use hugepages

### ISSUE THREAD

**Issue by kreuzerkrieg** [google/tcmalloc#47]
I mean 1GiB pages, looks like `tcmalloc` can use transparent huge pages out of the box. However I didnt findany evidence it can use 1GiB huge pages. In case it is not supported, is there a way just to feed the starting pointer and give it available memory size which I obtain from `mmap`?

**Comment by ckennelly** [comment]
You can use the `AddressRegionFactory` API ([here](https://github.com/google/tcmalloc/blob/master/tcmalloc/malloc_extension.h#L124)) to customize how memory is backed, which would give you an opportunity to customize how `mmap` is invoked.

**Comment by kreuzerkrieg** [comment]
looks like the only thing I have to do it implement the `Create (void* start_addr, size_t size, UsageHint hint)`. Easy-peasy. Thanks!

**Comment by kreuzerkrieg** [comment]
Finally, got a time to take a deeper look at it. Feels like not exactly what I was thinking of. It feels more appropriate to do the following. As I understand, `Arena` created statically and serves all allocations in the `tcmalloc`, more convenient place to achieve what I need is to modify `Arena::Alloc` with something like this.
```
if (free_area_ == nullptr) {
    uint8_t *const base_address =
        reinterpret_cast<uint8_t *>(0x100000000000ULL);
    size_t size = 128_GiB;
    int flags = MAP_ANONYMOUS | MAP_PRIVATE | MAP_FIXED | MAP_HUGETLB;
    void *arena =
        mmap(base_address, size, PROT_READ | PROT_WRITE, flags, -1, 0);
    if (arena == base_address) {
      free_area_ = reinterpret_cast<char *>(arena);
      free_avail_ = size;
    } else {
      std::string err_msg =
          "FATAL ERROR: Failed to open huge page memory. Reason: ";
      err_msg += std::strerror(errno);
      Crash(kCrash, __FILE__, __LINE__, err_msg.c_str(), kAllocIncrement, size,
            arena);
    }
  }

```
On first allocation, go ahead, allocate all the memory you need, save the size and pointer in the `Arena` and.. thats it. yes, you are supposed to fail once you reach memory limit, yes, it is not good solution for most cases, except one - when your application is sole occupant of the machine and it is the only thing running there, except OS of course. Something like storage or SQL server.

WDYT? would that approach work?

**Comment by ckennelly** [comment]
The Arena code in TCMalloc is only used for handling TCMalloc's own internal metadata allocations, which are relatively uninteresting for huge pages, since they're only accessed as part of the allocation process, rather than by the application itself.

The Address Region API handles the backing of allocations requested by the application.

The other important note is that since these are layering underneath `malloc` itself, standard libraries like `std::string` which might allocate can't be used.  In your example, `err_msg` and the concatentation operation might both allocate.

**Comment by kreuzerkrieg** [comment]
Ok, looks like I'll have to write a real code :) Thanks again
