### ISSUE TITLE
Disabling tcmalloc for asan/tsan runs when using bazel

### ISSUE THREAD

**Issue by HappyCerberus** [google/tcmalloc#53]
We use bazel as our build system.

How do I disable tcmalloc for asan/tsan runs when using the `malloc = "@com_google_tcmalloc//tcmalloc",` syntax?

**Comment by ckennelly** [comment]
You could depend on an intermediate build target that `select`'s for sanitizers and inserts an empty dependency list and fallback to TCMalloc for all other cases.

Alternatively, on sanitizer builds, you could specify `--custom_malloc=...` to pick an empty target that doesn't transitively provide TCMalloc.
