### ISSUE TITLE
tcmalloc not releasing memory vs kubernetes

### ISSUE THREAD

**Issue by HappyCerberus** [google/tcmalloc#59]
Hi, we are using tcmalloc inside of kubernetes and we keep seeing kubelets running over memory limits even though they have no reason to.

I have a suspicion that this is tcmalloc not releasing memory. Which is desirable, however not if it trips over the oom killswitch in kubernetes. Should we just use `ulimit`?

**Comment by ckennelly** [comment]
The [tuning guide](https://google.github.io/tcmalloc/tuning.html) has a few parameters for reducing memory usage.

Additionally, you might want to consider using the limit API in [`tcmalloc::MallocExtension::SetMemoryLimit`](https://github.com/google/tcmalloc/blob/master/tcmalloc/malloc_extension.h#L301).

The limit works in terms of TCMalloc-managed memory (it doesn't know about mmap'd data, the executable itself, thread stacks, etc.), but it will proactively return memory to the OS (including partial huge pages, which can carry a performance penalty for still-active allocations) if a new allocation would cause the limit to be exceeded.

**Comment by HappyCerberus** [comment]
Thanks for the info.
