### ISSUE TITLE
Viewing TCmalloc memory allocations

### ISSUE THREAD

**Issue by marcinguy** [google/tcmalloc#60]
Related to Chromium's TCmalloc, but maybe somebody here can help. 

Modified Chromium TTMalloc allocator to expose pagemap_ like below:

```
third_party/tcmalloc/chromium/src/page_heap.h

class PERFTOOLS_DLL_DECL PageHeap {
 public:
  PageHeap();
  typedef MapSelector<kAddressBits>::Type PageMap;
  PageMap pagemap_;

third_party/tcmalloc/chromium/src/static_vars.cc

PageHeap Static::pageheap2_;

third_party/tcmalloc/chromium/src/static_vars.h

static PageHeap pageheap2_;


```
Exposed PageHeap via pageheap2_, but somehow 3 radix tree does not contain data/pointers? Only "0"

My script (https://github.com/marcinguy/tcmalloc-inspector) shows the same:
```
USED:
BLOCK SUMMARY
0 blocks, 0 total size
size frequencies:
FREE:
BLOCK SUMMARY
0 blocks, 0 total size
size frequencies:
LOST:
BLOCK SUMMARY
0 blocks, 0 total size
size frequencies:
```
More GDB output here: https://github.com/marcinguy/tcmalloc-chromium

Any idea why?

Did I modify the TCMalloc wrongly?

With Google's Tcmalloc in another sample program ia works correctly. 

https://github.com/marcinguy/tcmalloc-inspector

Thanks,

**Comment by ckennelly** [comment]
As of writing this comment, Chromium uses a variant of https://github.com/gperftools/gperftools.  It has a number of local patches to it which modify internal data structures.  This might be interfering with your script.
