### ISSUE TITLE
built .so from latest master fails to load because of 'undefined symbol' on Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by repu1sion** [google/tcmalloc#61]
After changing in BUILD file linkstatic = 1 to 0 and running bazel build //tcmalloc build seems to be ok.

```
ldd /usr/local/lib/libtcmalloc.so 
	linux-vdso.so.1 (0x00007fff104e5000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/debug/libstdc++.so.6 (0x00007f7ab7b10000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f7ab7772000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f7ab755a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f7ab7169000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7ab7ec9000)
```
But attempts to use it, like open it with dlopen() from C++ code  fail because of undefined symbol:
```
./loader 
C++ dlopen demo

Opening tcmalloc.so...
Cannot open library: /usr/local/lib/libtcmalloc.so: undefined symbol: _ZN4absl19str_format_internal13FormatArgImpl8DispatchINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEbNS1_4DataENS0_24FormatConversionSpecImplEPv
```
Is it old libstdc++ version, or old gcc version (7.5.0)? Any sane list of requirements or a doc about how to build it ?

**Comment by ckennelly** [comment]
This is a symbol that is provided by Abseil, which also needs to be linked in.

Loading TCMalloc via dlopen is [not supported](https://google.github.io/tcmalloc/compatibility.html).  With memory allocators in particular, allocations need to be correctly deallocated to the implementation that allocated them.  For `new` and `malloc`, these are global symbols.

**Comment by karanaggarwal1994** [comment]
How to link abseil in tcmalloc.so?
