### ISSUE TITLE
libtcmalloc_minimal.so is missing

### ISSUE THREAD

**Issue by zhangguanheng66** [google/tcmalloc#64]
I tried to compile sentencepiece locally and got the follow error. Any help are appreciated:

```
[ 16%] Built target sentencepiece_train-static
[ 83%] Built target sentencepiece-static
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so', needed by 'src/spm_normalize'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:104: src/CMakeFiles/spm_normalize.dir/all] Error 2
```

Of course, `libtcmalloc_minimal.so` is not in the folder of `/usr/lib/x86_64-linux-gnu/`. Any ideas to install it. Thx.

**Comment by ckennelly** [comment]
This project does not provide a `libtcmalloc_minimal.so` target.
