### ISSUE TITLE
Does the tcmalloc support QNX？ 

### ISSUE THREAD

**Issue by stoneboy100200** [google/tcmalloc#69]
Could you please tell me the tcmalloc support QNX OS?

**Comment by ckennelly** [comment]
No.  Our list of supported platforms is documented here: https://google.github.io/tcmalloc/platforms

**Comment by stoneboy100200** [comment]
> No. Our list of supported platforms is documented here: https://google.github.io/tcmalloc/platforms

Is there any other way to use tcmalloc on QNX? It is very important to use tcmalloc, so please let me know if there is any other way. Thanks very much！

**Comment by MiloMallo** [comment]
go to gperftools
