### ISSUE TITLE
Turning off linkstatic = 1 does not produce dynamic libraries. 

### ISSUE THREAD

**Issue by jaidayal** [google/tcmalloc#71]
I followed the guidance listed here (https://github.com/google/tcmalloc/issues/27) on how to build a static library. In the various BUILD files, I commented out the linkstatic = 1 lines, however, I can't find any .so files produced:

find tcmalloc/ -name *.so

Since I'm on a SLES 15 HPC cluster, I can't install packages through zypper/apt/yum (no root access) so I am not sure how I can generate a .so file.

**Comment by ckennelly** [comment]
Bazel places binaries in `bazel-bin`.

```
$ git diff | cat
diff --git a/tcmalloc/BUILD b/tcmalloc/BUILD
index 97e2f72..523d742 100644
--- a/tcmalloc/BUILD
+++ b/tcmalloc/BUILD
@@ -88,7 +88,6 @@ cc_library(
         "tcmalloc.h",
     ],
     copts = TCMALLOC_DEFAULT_COPTS,
-    linkstatic = 1,
     visibility = ["//visibility:public"],
     deps = tcmalloc_deps + [
         ":common",
$ bazel build //tcmalloc:tcmalloc
Starting local Bazel server and connecting to it...
INFO: Analyzed target //tcmalloc:tcmalloc (32 packages loaded, 442 targets configured).
INFO: Found 1 target...
Target //tcmalloc:tcmalloc up-to-date:
  bazel-bin/tcmalloc/libtcmalloc.lo
  bazel-bin/tcmalloc/libtcmalloc.so
INFO: Elapsed time: 19.190s, Critical Path: 5.23s
INFO: 108 processes: 108 processwrapper-sandbox.
INFO: Build completed successfully, 111 total actions
$ find bazel-bin/tcmalloc/ -name '*.so'
bazel-bin/tcmalloc/libtcmalloc.so
```

That said, the `libtcmalloc.so` will have further deps (like on Abseil), so those will need to be findable by the loader.

**Comment by karanaggarwal1994** [comment]
How to link abseil in tcmalloc.so?
