### ISSUE TITLE
Infinite loop on concurrent allocations

### ISSUE THREAD

**Issue by ayles** [google/tcmalloc#75]
When `realloc` or similar function is called on same memory from two threads without sync i assume that program will crash.
But with TCMalloc it doesn't.

Minimal reproducible example:
Create `std::vector<double>` and push elements to it from two different threads without any locks, then suddenly  program will stuck with infinite memory allocating loop until it dies from oom killer.

Infinite loop is here:
https://github.com/google/tcmalloc/blob/master/tcmalloc/peak_heap_tracker.cc#L63
cause `Static::sampled_objects_.head_.next_` points to itself with `next_` and `prev_`.
It is caused by the fact that both threads receive same `Span` object from `HugePageAwareAllocator` here:
https://github.com/google/tcmalloc/blob/master/tcmalloc/tcmalloc.cc#L1481

I am little confused why, cause `HugePageAwareAllocator` takes `pageheap_lock` before any allocations.
We are using TCMalloc from commit `a643d89610317be1eff9f7298104eef4c987d8d5`.
This bug is kinda critical in production where such races can pop up so I hope it can be fixed soon (or maybe it is fixed in newer versions?).

bt:

```
tcmalloc::PeakHeapTracker::MaybeSaveSample (this=0x4ff3c0 <tcmalloc::Static::peak_heap_tracker_>) at .../libs/tcmalloc/tcmalloc/peak_heap_tracker.cc:70
(anonymous namespace)::SampleifyAllocation (requested_size=0, requested_size@entry=2097152, weight=<optimized out>, requested_alignment=<optimized out>, requested_alignment@entry=1, cl=cl@entry=0, obj=obj@entry=0x0, span=span@entry=0x47447ec005e0, capacity=0x0) at .../libs/tcmalloc/tcmalloc/tcmalloc.cc:1469
(anonymous namespace)::do_malloc_pages (size=2097152, alignment=1) at .../libs/tcmalloc/tcmalloc/tcmalloc.cc:1529
slow_alloc<tcmalloc::TCMallocPolicy<tcmalloc::CppOomPolicy, tcmalloc::DefaultAlignPolicy, tcmalloc::InvokeHooksPolicy>, decltype(nullptr)>(tcmalloc::TCMallocPolicy<tcmalloc::CppOomPolicy, tcmalloc::DefaultAlignPolicy, tcmalloc::InvokeHooksPolicy>, unsigned long, decltype(nullptr)) (policy=..., size=2097152, capacity=<optimized out>) at .../libs/tcmalloc/tcmalloc/tcmalloc.cc:1826
std::__y1::__libcpp_allocate (__size=78420757185056, __align=8) at .../libs/cxxsupp/libcxx/include/new:261
std::__y1::allocator<double>::allocate (this=<optimized out>, __n=262144) at .../libs/cxxsupp/libcxx/include/memory:1869
std::__y1::allocator_traits<std::__y1::allocator<double> >::allocate (__a=..., __n=262144) at .../libs/cxxsupp/libcxx/include/memory:1585
std::__y1::__split_buffer<double, std::__y1::allocator<double>&>::__split_buffer (this=<optimized out>, __cap=262144, __start=131072, __a=...) at .../libs/cxxsupp/libcxx/include/__split_buffer:326
std::__y1::vector<double, std::__y1::allocator<double> >::__push_back_slow_path<double> (this=0x7ffd69d3c2e0, __x=<optimized out>) at .../libs/cxxsupp/libcxx/include/vector:1660
std::__y1::vector<double, std::__y1::allocator<double> >::push_back (this=0x7ffd69d3c2e0, __x=<optimized out>) at .../libs/cxxsupp/libcxx/include/vector:1692
```

**Comment by ckennelly** [comment]
I might be misunderstanding your reproducer, but I think your program has a race condition.

Accessing `std::vector` from two threads without a lock is a data race (and so is undefined behavior)  This may cause a double-free as the two threads separately decide they need to resize and free the memory to TCMalloc.  Double frees are also undefined behavior.

If you run your program under Address Sanitizer and/or Thread Sanitizer, is it correct or is undefined behavior flagged?

**Comment by ayles** [comment]
Yep, this is data race (and, respectively, UB), and asan/tsan show it, but in real world in large applications it happens. And in this case, I would like to see service crash with coredump, and not hang for a long time with increasing memory usage

**Comment by ckennelly** [comment]
Going back to your initial post, though:
* `HugePageAwareAllocator` needs to take `pageheap_lock` to guard its shared state.
* You mentioned that the same `Span` is returned.  Is this the `Span` corresponding to the double-free'd block?

TCMalloc is optimized for performance, so we do not have substantial technical defenses against undefined behavior.  Tools like [GWP-ASan](https://google.github.io/tcmalloc/gwp-asan.html) built into TCMalloc can detect some of these, using probabilistic techniques to reduce the performance overhead.

For non-optimized builds, some of our assertions can catch various bugs, even from UB, but it has limitations.

**Comment by ayles** [comment]
Here is minimal example with recent TCMalloc:
https://github.com/ayles/tcmalloc_ub_lock

I will check on the weekend if that `Span` is the same as double-free'd block `Span`.

As for the example - it is worth mention that the hang appears only in this `malloc` - `free` order and only in release (`--compilation_mode=opt`) mode, on debug it fails on assert:
`external/com_google_tcmalloc/tcmalloc/tcmalloc.cc:1544] span->first_page() == p`

**Comment by ckennelly** [comment]
It is unfortunately not practical to add complete defenses against undefined behavior in optimized builds, since that can hamper performance in correct programs.  There is not a good way to allow this to work cleanly.

* The infinite loop is a symptom of invariants failing, but it's possible the bug would manifest in other ways, even if `PeakHeapTracker` were hardened against that.  For example, when reading the heap profile with `malloc_extension.h`'s APIs, we might encounter the broken linked list there instead.
* The methods we do have will crash loudly, but crash nonetheless:
  * [GWP-ASan](https://google.github.io/tcmalloc/gwp-asan.html) is a bit of a balance between finding UB while keeping the overheads low, but it does so by using statistical methods.  That said, it does intentionally crash when UB is detected, just like AddressSanitizer does.
  * Since you noted an assertion failure:  The `//tcmalloc:opt_with_assertions` target builds with assertions enabled on all builds.

**Comment by ayles** [comment]
Is there any way to disable heap track with defines or with calls to config functions?

**Comment by ckennelly** [comment]
You can turn off heap sampling with `tcmalloc::MallocExtension::SetProfileSamplingRate` with a negative value, but there might be other invariants that break elsewhere given the undefined behavior.
