### ISSUE TITLE
Implement mallinfo2

### ISSUE THREAD

**Issue by gjasny** [google/tcmalloc#80]
Hello,

recent glibc versions started to issue a deprecation warning for `mallinfo`. Could you please implement the successor [mallinfo2](https://man7.org/linux/man-pages/man3/mallinfo.3.html)?

Thanks,
Gregor

**Comment by junyer** [comment]
@jcking did this in https://github.com/google/tcmalloc/commit/780744bb58f75887d53eb6d088f141e9c16b829e a couple of weeks ago.

**Comment by gjasny** [comment]
Thanks for noticing.
