### ISSUE TITLE
tcmalloc does not support iOS?

### ISSUE THREAD

**Issue by gaxlin** [google/tcmalloc#86]
I try compile for iOS target but failed! it tells :
_dyld_present' is deprecated: first deprecated in macOS 10.5 - always true

**Comment by ckennelly** [comment]
Correct, only Linux is supported: https://google.github.io/tcmalloc/platforms.html.

**Comment by gaxlin** [comment]
could we support ios?like mimalloc?

**Comment by gaxlin** [comment]
how about android system? arm targets?
