### ISSUE TITLE
Crash:free pointer which create by strdup 

### ISSUE THREAD

**Issue by cwclive2** [google/tcmalloc#90]
IDE: VS2019  win32
Version: gperftools-2.9.1
3rdlibs: Ws2_32.lib;psapi.lib;Crypt32.lib;wldap32.lib;%(AdditionalDependencies);kernel32.lib;user32.lib;gdi32.lib;winspool.lib;comdlg32.lib;advapi32.lib;shell32.lib;ole32.lib;oleaut32.lib;uuid.lib;odbc32.lib;odbccp32.lib;msvcrtd.lib;winmm.lib

code:
`
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

void main()
{
    char* a= strdup("just test");
    free(a);
}
`

strdup do not call tc_malloc or tc_calloc.
free do call tc_free

crash message: [gperftools-2.9.1\src\tcmalloc.cc:333] Attempt to free invalid pointer 0x4a86048

**Comment by vlovich** [comment]
@cwclive2 did you mean to file this against https://github.com/gperftools/gperftools?

**Comment by ckennelly** [comment]
This looks like it should be filed against https://github.com/gperftools/gperftools.

It looks like libc's `strdup` may be calling libc's own `malloc`, rather than the provided allocator, causing a mismatch.
