### ISSUE TITLE
Using tcmalloc in a sandbox and cpuset file access?

### ISSUE THREAD

**Issue by vlovich** [google/tcmalloc#96]
The [rseq code](https://github.com/google/tcmalloc/blob/master/tcmalloc/internal/percpu.cc#L241) appears to access /proc/self/cpuset. We run in a sandbox so I'm curious if we've simply misconfigured TCMalloc (maybe this path is only used if we've accidentally not enabled rseq?) or if this file is required to be accessed from the sandbox and we need to make it available.

**Comment by ckennelly** [comment]
This file is used to provide cross-CPU synchronization when using restartable sequences.  Restartable sequences heavily optimize for the same-core case, but cross-CPU requires a bit more work.

That said, if the `membarrier` syscall--and is [sufficiently up to date](https://github.com/torvalds/linux/commit/2a36ab717e8fe678d98f81c14a0b124712719840)--is available, it is used preferentially.

**Comment by vlovich** [comment]
Yeah, we have a configuration where we are running an older kernel unfortunately so I'm trying to figure out what we can do. If we bind mount `cpuset` before entering the sandbox in process A, then we enter the sandbox & fork process B, is it a problem that B would be pointing to the same `cpuset` as A? I'm assuming no & the cpuset file needs to be the correct one for the process but just double-checking.
